/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.principal;
                 
import Classes.ClassePrincipal;
import Classes.FuncionarioLogado;
import com.towel.swing.img.JImagePanel;
import imagens.fundos.BGDesktopPane;
import imagens.fundos.ImagemPrincipal;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JToolBar;
import telas.atendimento.CadastrarCliente;
import telas.atendimento.Ligações;
import telas.atendimento.PesquisarClientes;
import telas.atendimento.PesquisarProdutos;
import telas.gestor.CadastrarFuncionarios;
import telas.gestor.ManterProdutos;
import telas.gestor.PesquisarFuncionarios;
import telas.supervisao.LogFuncionarios;
import telas.supervisao.RelatorioLigaçoes;
import utilitarios.BlocoNotas;
import utilitarios.Calculadora;

/**
 *
 * @author User
 */
public class Principal extends javax.swing.JFrame {
    
    private static Principal p;
    public static Principal getInstancia(){
        if (p==null){
            p= new Principal();
        }
        return p;
    }
      public static JDesktopPane getPainel(){
         return getInstancia().AreaPrincipal;
     }
    public static JToolBar getMenu(){
         return getInstancia().MenuCargos;
     }

    CadastrarCliente cadastrarCliente = new CadastrarCliente();
    Ligações ligações = new Ligações();
    PesquisarClientes pesquisarCliente = new PesquisarClientes();
    PesquisarProdutos pesquisarProdutos = new PesquisarProdutos();

    CadastrarFuncionarios cadastrarFuncionarios = new CadastrarFuncionarios();
    ManterProdutos manterProdutos = new ManterProdutos();
    PesquisarFuncionarios pesquisarFuncionarios = new PesquisarFuncionarios();
        
    LogFuncionarios logFuncionarios = new LogFuncionarios();
    RelatorioLigaçoes relatorioLigaçoes = new RelatorioLigaçoes();

    BlocoNotas blocoNotas = new BlocoNotas();
    Calculadora calculadora = new Calculadora();
    
     

    public Principal() {
        initComponents();
         
            
        
        //AreaPrincipal.setBorder(new ImagemPrincipal());
        //this.setExtendedState(Principal.MAXIMIZED_BOTH);
        AreaPrincipal.add(cadastrarCliente);
        AreaPrincipal.add(ligações);
        AreaPrincipal.add(pesquisarCliente);
        AreaPrincipal.add(pesquisarProdutos);

        AreaPrincipal.add(logFuncionarios);
        AreaPrincipal.add(relatorioLigaçoes);

        AreaPrincipal.add(cadastrarFuncionarios);
        AreaPrincipal.add(manterProdutos);
        AreaPrincipal.add(pesquisarFuncionarios);
      
        AreaPrincipal.add(blocoNotas);
        AreaPrincipal.add(calculadora);
        
        
        AtCadastrarCliente.setVisible(false);
        AtPesquisarClientes.setVisible(false);
        AtPesquisarProduto.setVisible(false);
        SupAtendimento.setVisible(false);
        
        SupRelLigaçoes.setVisible(false);
        GestCadastroFunc.setVisible(false);
        GestPesqFunc.setVisible(false);
        GestCrtlProdutos.setVisible(false);
             
             
    }
        
        FuncionarioLogado f = new FuncionarioLogado();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PainelMenu = new javax.swing.JPanel();
        MenuCargos = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        AtCadastrarCliente = new javax.swing.JButton();
        AtPesquisarClientes = new javax.swing.JButton();
        AtPesquisarProduto = new javax.swing.JButton();
        Separador2 = new javax.swing.JToolBar.Separator();
        SupRelLigaçoes = new javax.swing.JButton();
        SupAtendimento = new javax.swing.JButton();
        GestPesqFunc = new javax.swing.JButton();
        Separador3 = new javax.swing.JToolBar.Separator();
        GestCadastroFunc = new javax.swing.JButton();
        GestCrtlProdutos = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        pBoasVindas = new javax.swing.JPanel();
        LbMensagem = new javax.swing.JLabel();
        LinkNome = new javax.swing.JLabel();
        AreaPrincipal = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        Menu = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        mlogin = new javax.swing.JMenuItem();
        mlogout = new javax.swing.JMenuItem();
        mUtilitarios = new javax.swing.JMenu();
        mcalculadora = new javax.swing.JMenuItem();
        mBlocoNotas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal SpimFlex");

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        PainelMenu.setBackground(new java.awt.Color(153, 255, 153));
        PainelMenu.setAlignmentX(0.1F);
        PainelMenu.setAlignmentY(0.1F);

        MenuCargos.setBackground(new java.awt.Color(204, 255, 204));
        MenuCargos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MenuCargos.setRollover(true);
        MenuCargos.setBorderPainted(false);
        MenuCargos.setEnabled(false);
        MenuCargos.setOpaque(false);
        MenuCargos.add(jSeparator1);

        AtCadastrarCliente.setBackground(new java.awt.Color(255, 255, 255));
        AtCadastrarCliente.setText("Cadastrar Clientes");
        AtCadastrarCliente.setFocusable(false);
        AtCadastrarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AtCadastrarCliente.setOpaque(false);
        AtCadastrarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AtCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtCadastrarClienteActionPerformed(evt);
            }
        });
        MenuCargos.add(AtCadastrarCliente);

        AtPesquisarClientes.setBackground(new java.awt.Color(255, 255, 255));
        AtPesquisarClientes.setText("Pesquisar Clientes");
        AtPesquisarClientes.setFocusable(false);
        AtPesquisarClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AtPesquisarClientes.setOpaque(false);
        AtPesquisarClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AtPesquisarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtPesquisarClientesActionPerformed(evt);
            }
        });
        MenuCargos.add(AtPesquisarClientes);

        AtPesquisarProduto.setBackground(new java.awt.Color(255, 255, 255));
        AtPesquisarProduto.setText("Pesquisar Produtos");
        AtPesquisarProduto.setFocusable(false);
        AtPesquisarProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AtPesquisarProduto.setOpaque(false);
        AtPesquisarProduto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AtPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtPesquisarProdutoActionPerformed(evt);
            }
        });
        MenuCargos.add(AtPesquisarProduto);
        MenuCargos.add(Separador2);

        SupRelLigaçoes.setBackground(new java.awt.Color(255, 255, 255));
        SupRelLigaçoes.setText("Relatório de Ligações");
        SupRelLigaçoes.setFocusable(false);
        SupRelLigaçoes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SupRelLigaçoes.setOpaque(false);
        SupRelLigaçoes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SupRelLigaçoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupRelLigaçoesActionPerformed(evt);
            }
        });
        MenuCargos.add(SupRelLigaçoes);

        SupAtendimento.setBackground(new java.awt.Color(255, 255, 255));
        SupAtendimento.setText("Painel de Atendimento");
        SupAtendimento.setFocusable(false);
        SupAtendimento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SupAtendimento.setOpaque(false);
        SupAtendimento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SupAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupAtendimentoActionPerformed(evt);
            }
        });
        MenuCargos.add(SupAtendimento);

        GestPesqFunc.setBackground(new java.awt.Color(255, 255, 255));
        GestPesqFunc.setText("Pesquisar Funcionario");
        GestPesqFunc.setFocusable(false);
        GestPesqFunc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GestPesqFunc.setOpaque(false);
        GestPesqFunc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        GestPesqFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestPesqFuncActionPerformed(evt);
            }
        });
        MenuCargos.add(GestPesqFunc);
        MenuCargos.add(Separador3);

        GestCadastroFunc.setBackground(new java.awt.Color(255, 255, 255));
        GestCadastroFunc.setText("Cadastrar Funcionario");
        GestCadastroFunc.setFocusable(false);
        GestCadastroFunc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GestCadastroFunc.setOpaque(false);
        GestCadastroFunc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        GestCadastroFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestCadastroFuncActionPerformed(evt);
            }
        });
        MenuCargos.add(GestCadastroFunc);

        GestCrtlProdutos.setBackground(new java.awt.Color(255, 255, 255));
        GestCrtlProdutos.setText("Cadastrar Produtos");
        GestCrtlProdutos.setFocusable(false);
        GestCrtlProdutos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GestCrtlProdutos.setOpaque(false);
        GestCrtlProdutos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        GestCrtlProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestCrtlProdutosActionPerformed(evt);
            }
        });
        MenuCargos.add(GestCrtlProdutos);
        MenuCargos.add(jSeparator4);

        javax.swing.GroupLayout PainelMenuLayout = new javax.swing.GroupLayout(PainelMenu);
        PainelMenu.setLayout(PainelMenuLayout);
        PainelMenuLayout.setHorizontalGroup(
            PainelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenuCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        PainelMenuLayout.setVerticalGroup(
            PainelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelMenuLayout.createSequentialGroup()
                .addComponent(MenuCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pBoasVindas.setBackground(new java.awt.Color(204, 255, 204));

        LbMensagem.setText("     Bem Vindo a SpimFlex:");

        LinkNome.setText("Faça seu Login.");
        LinkNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LinkNomeMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pBoasVindasLayout = new javax.swing.GroupLayout(pBoasVindas);
        pBoasVindas.setLayout(pBoasVindasLayout);
        pBoasVindasLayout.setHorizontalGroup(
            pBoasVindasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBoasVindasLayout.createSequentialGroup()
                .addComponent(LbMensagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LinkNome)
                .addGap(0, 699, Short.MAX_VALUE))
        );
        pBoasVindasLayout.setVerticalGroup(
            pBoasVindasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pBoasVindasLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(pBoasVindasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbMensagem)
                    .addComponent(LinkNome)))
        );

        AreaPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        AreaPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 255, 153), new java.awt.Color(102, 255, 153)));
        AreaPrincipal.setOpaque(false);

        javax.swing.GroupLayout AreaPrincipalLayout = new javax.swing.GroupLayout(AreaPrincipal);
        AreaPrincipal.setLayout(AreaPrincipalLayout);
        AreaPrincipalLayout.setHorizontalGroup(
            AreaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 878, Short.MAX_VALUE)
        );
        AreaPrincipalLayout.setVerticalGroup(
            AreaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pBoasVindas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AreaPrincipal))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pBoasVindas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(PainelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AreaPrincipal)
                .addGap(6, 6, 6))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(85, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        Menu.setBackground(new java.awt.Color(255, 255, 255));

        jMenu3.setText("Menu");

        mlogin.setText("Log-in");
        mlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mloginActionPerformed(evt);
            }
        });
        jMenu3.add(mlogin);

        mlogout.setText("Log-Out");
        mlogout.setEnabled(false);
        jMenu3.add(mlogout);

        Menu.add(jMenu3);

        mUtilitarios.setText("Utilitarios");

        mcalculadora.setText("Calculadora");
        mUtilitarios.add(mcalculadora);

        mBlocoNotas.setText("Bloco de Notas");
        mUtilitarios.add(mBlocoNotas);

        Menu.add(mUtilitarios);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(918, 578));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AtCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtCadastrarClienteActionPerformed
        cadastrarCliente.setVisible(true);
    }//GEN-LAST:event_AtCadastrarClienteActionPerformed

    private void mloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mloginActionPerformed
        
    }//GEN-LAST:event_mloginActionPerformed

    private void LinkNomeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LinkNomeMouseReleased
       
    }//GEN-LAST:event_LinkNomeMouseReleased

    private void AtPesquisarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtPesquisarClientesActionPerformed
        pesquisarCliente.setVisible(true); 
                  
    }//GEN-LAST:event_AtPesquisarClientesActionPerformed

    private void AtPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtPesquisarProdutoActionPerformed
        pesquisarProdutos.setVisible(true);
    }//GEN-LAST:event_AtPesquisarProdutoActionPerformed

    private void SupRelLigaçoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupRelLigaçoesActionPerformed
        relatorioLigaçoes.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_SupRelLigaçoesActionPerformed

    private void SupAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupAtendimentoActionPerformed
        ligações.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_SupAtendimentoActionPerformed

    private void GestCadastroFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestCadastroFuncActionPerformed
        cadastrarFuncionarios.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_GestCadastroFuncActionPerformed

    private void GestPesqFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestPesqFuncActionPerformed
        pesquisarFuncionarios.setVisible(true);           // TODO add your handling code here:
    }//GEN-LAST:event_GestPesqFuncActionPerformed

    private void GestCrtlProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestCrtlProdutosActionPerformed
        manterProdutos.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_GestCrtlProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }   
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
              new Principal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane AreaPrincipal;
    public javax.swing.JButton AtCadastrarCliente;
    public javax.swing.JButton AtPesquisarClientes;
    public javax.swing.JButton AtPesquisarProduto;
    public javax.swing.JButton GestCadastroFunc;
    public javax.swing.JButton GestCrtlProdutos;
    public javax.swing.JButton GestPesqFunc;
    public javax.swing.JLabel LbMensagem;
    public javax.swing.JLabel LinkNome;
    public javax.swing.JMenuBar Menu;
    public javax.swing.JToolBar MenuCargos;
    public javax.swing.JPanel PainelMenu;
    public javax.swing.JToolBar.Separator Separador2;
    public javax.swing.JToolBar.Separator Separador3;
    public javax.swing.JButton SupAtendimento;
    public javax.swing.JButton SupRelLigaçoes;
    public javax.swing.JMenu jMenu3;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JToolBar.Separator jSeparator1;
    public javax.swing.JToolBar.Separator jSeparator4;
    public javax.swing.JMenuItem mBlocoNotas;
    public javax.swing.JMenu mUtilitarios;
    public javax.swing.JMenuItem mcalculadora;
    public javax.swing.JMenuItem mlogin;
    public javax.swing.JMenuItem mlogout;
    public javax.swing.JPanel pBoasVindas;
    // End of variables declaration//GEN-END:variables

     public static BufferedImage loadImage(String file) throws IOException {
        return ImageIO.read(new File(file));
    }
   
   }  
  
 
    
