/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package telas.atendimento;

import Classes.ClassePrincipal;
import DAO.ClienteDAO;
import DAO.EnderecosDAO;
import DAO.PFisicaDAO;
import DAO.PJuridicaDAO;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import utilitarios.CalendarComboBox;
import utilitarios.Formato;

/**
 *
 * @author User
 */
public class CadastrarCliente extends javax.swing.JInternalFrame {
    

    /**
     * Creates new form CadastrarCliente
     */
    public CadastrarCliente() {
        initComponents();
        btnSalvar.setVisible(false);
        btnCancel.setVisible(false);
        btnNovo.setEnabled(true);
        btnPesq.setEnabled(true);
        btnNovoPJ.setEnabled(true);
        btnCancelarPJ.setVisible(false);
        btnSalvarPJ.setVisible(false);
        btnPesqPJ.setEnabled(true);
        
        
        
        
        txtBairro.setEnabled(false);
        txtCep.setEnabled(false);
        txtCidade.setEnabled(false);
        txtComplemento.setEnabled(false);
        txtCpf.setEnabled(false);
        txtEmail.setEnabled(false);
        txtFone1.setEnabled(false);
        txtFone2.setEnabled(false);
        txtNome.setEnabled(false);
        txtNumero.setEnabled(false);
        txtRua.setEnabled(false);
        txtSenha.setEnabled(false);
        jDateChooser1.setEnabled(false);
        
        cbEstado.setEnabled(false);
        cbPJEstados.setEnabled(false);
        
        txtPJCep.setEnabled(false);
        txtPJCidade.setEnabled(false);
        txtPJCnpj.setEnabled(false);
        txtPJComplemento.setEnabled(false);
        txtPJEmail.setEnabled(false);
        txtPJFone1.setEnabled(false);
        txtPJFone2.setEnabled(false);
        txtPJNome.setEnabled(false);
        txtPJNumero.setEnabled(false);
        txtPJRazao.setEnabled(false);
        txtPJSenha.setEnabled(false);
        txtPJRua.setEnabled(false);
        txtResponsavel.setEnabled(false);
        txtPJBairro.setEnabled(false);
        
        txtBairro.setText("");
        txtCep.setText("");
        txtCidade.setText("");
        txtComplemento.setText("");
        txtCpf.setText("");
        txtEmail.setText("");
        txtFone1.setText("");
        txtFone2.setText("");
        txtNome.setText("");
        txtNumero.setText("");
        txtRua.setText("");
        txtSenha.setText("");
        
        
        txtPJCep.setText("");
        txtPJCidade.setText("");
        txtPJCnpj.setText("");
        txtPJComplemento.setText("");
        txtPJEmail.setText("");
        txtPJFone1.setText("");
        txtPJFone2.setText("");
        txtPJNome.setText("");
        txtPJNumero.setText("");
        txtPJRazao.setText("");
        txtPJSenha.setText("");
        txtPJRua.setText("");
        txtResponsavel.setText("");
        txtPJBairro.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        txtCpf = Formato.getCPF();
        jLabel9 = new javax.swing.JLabel();
        txtFone1 = Formato.getTelefoneFixo();
        txtFone2 = Formato.getTelefoneCelular();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtComplemento = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtCep = Formato.getCep();
        cbEstado = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnPesq = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        txtResponsavel = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPJEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPJSenha = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPJFone1 = Formato.getTelefoneFixo();
        jLabel14 = new javax.swing.JLabel();
        txtPJFone2 = Formato.getTelefoneCelular();
        lbCnpj = new javax.swing.JLabel();
        txtPJCnpj = Formato.getCNPJ();
        jLabel1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtPJRua = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtPJNumero = new javax.swing.JTextField();
        txtPJComplemento = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtPJBairro = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtPJCidade = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        cbPJEstados = new javax.swing.JComboBox();
        txtPJCep = Formato.getCep();
        jLabel31 = new javax.swing.JLabel();
        btnNovoPJ = new javax.swing.JButton();
        btnPesqPJ = new javax.swing.JButton();
        btnSalvarPJ = new javax.swing.JButton();
        btnCancelarPJ = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        txtPJRazao = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtPJNome = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setForeground(java.awt.Color.white);
        setResizable(true);
        setTitle("Clientes");

        jTabbedPane3.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        Logo.setText("Cadastro de Clientes");

        jLabel2.setText("Nome:");

        jLabel3.setText("E-mail:");

        jLabel4.setText("Senha:");

        jLabel5.setText("Telefone:");

        jLabel6.setText("Celular:");

        jLabel8.setText("CPF:");

        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });

        jLabel9.setText("Data Nasc:");

        txtFone2.setToolTipText("");

        jLabel16.setText("Rua:");

        jLabel17.setText("Numero:");

        jLabel18.setText("Complemento:");

        jLabel19.setText("Bairro:");

        jLabel20.setText("Cidade:");

        jLabel21.setText("Estado:");

        jLabel22.setText("CEP:");

        txtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroActionPerformed(evt);
            }
        });

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Estados", "Acre (AC)", "Alagoas (AL)", "Amapá (AP)", "Amazonas (AM)", "Bahia (BA)", "Ceará (CE)", "Distrito Federal (DF)", "Espírito Santo (ES)", "Goiás (GO)", "Maranhão (MA)", "Mato Grosso (MT)", "Mato Grosso do Sul (MS)", "Minas Gerais (MG)", "Pará (PA)", "Paraíba (PB)", "Paraná (PR)", "Pernambuco (PE)", "Piauí (PI)", "Rio de Janeiro (RJ)", "Rio Grande do Norte (RN)", "Rio Grande do Sul (RS)", "Rondônia (RO)", "Roraima (RR)", "Santa Catarina (SC)", "São Paulo (SP)", "Sergipe (SE)", "Tocantins (TO)" }));

        jLabel23.setText("Endereço");

        btnSalvar.setText("Cadastrar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnPesq.setText("Pesquisar");
        btnPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addComponent(txtFone1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addComponent(txtFone2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSenha)
                            .addComponent(txtCpf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(Logo))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel22)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel17)
                                                .addComponent(jLabel19)
                                                .addComponent(jLabel20)
                                                .addComponent(jLabel21)))
                                        .addComponent(jLabel18)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtBairro, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtComplemento, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNumero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbEstado, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                                    .addComponent(txtCep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel23)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Logo)
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtFone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtFone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnCancel)
                    .addComponent(btnPesq)
                    .addComponent(btnSalvar))
                .addContainerGap())
        );

        jTabbedPane3.addTab("Pessoa Física", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setText("Responsável:");

        jLabel11.setText("E-mail:");

        jLabel12.setText("Senha:");

        jLabel13.setText("Telefone:");

        jLabel14.setText("Celular:");

        txtPJFone2.setToolTipText("");

        lbCnpj.setText("CNPJ:");

        txtPJCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPJCnpjActionPerformed(evt);
            }
        });

        jLabel1.setText("EmpresasLogo");

        jLabel24.setText("Endereço");

        jLabel25.setText("Rua:");

        jLabel26.setText("Numero:");

        jLabel27.setText("Complemento:");

        txtPJBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPJBairroActionPerformed(evt);
            }
        });

        jLabel28.setText("Bairro:");

        jLabel29.setText("Cidade:");

        jLabel30.setText("Estado:");

        cbPJEstados.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Estados", "Acre (AC)", "Alagoas (AL)", "Amapá (AP)", "Amazonas (AM)", "Bahia (BA)", "Ceará (CE)", "Distrito Federal (DF)", "Espírito Santo (ES)", "Goiás (GO)", "Maranhão (MA)", "Mato Grosso (MT)", "Mato Grosso do Sul (MS)", "Minas Gerais (MG)", "Pará (PA) ", "Paraíba (PB)", "Paraná (PR)", "Pernambuco (PE)", "Piauí (PI)", "Rio de Janeiro (RJ)", "Rio Grande do Norte (RN)", "Rio Grande do Sul (RS)", "Rondônia (RO)", "Roraima (RR)", "Santa Catarina (SC)", "São Paulo (SP)", "Sergipe (SE)", "Tocantins (TO)" }));

        jLabel31.setText("CEP:");

        btnNovoPJ.setText("Novo");
        btnNovoPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoPJActionPerformed(evt);
            }
        });

        btnPesqPJ.setText("Pesquisar");
        btnPesqPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqPJActionPerformed(evt);
            }
        });

        btnSalvarPJ.setText("Cadastrar");
        btnSalvarPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarPJActionPerformed(evt);
            }
        });

        btnCancelarPJ.setText("Cancelar");
        btnCancelarPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPJActionPerformed(evt);
            }
        });

        jLabel32.setText("Razão Social:");

        jLabel33.setText("Empresa:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel33))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPJFone1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPJFone2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPJSenha)
                            .addComponent(txtPJEmail)
                            .addComponent(txtResponsavel, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(txtPJNome)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel32)
                            .addComponent(lbCnpj))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPJCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPJRazao, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel24)
                        .addGap(141, 141, 141))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel26)
                                        .addComponent(jLabel28)
                                        .addComponent(jLabel29)
                                        .addComponent(jLabel30)))
                                .addComponent(jLabel27))
                            .addComponent(jLabel25)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPJBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(txtPJComplemento, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbPJEstados, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                                .addComponent(txtPJNumero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPJCep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPJCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPJRua))
                        .addContainerGap())))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnNovoPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesqPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalvarPJ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelarPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel24))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPJRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(txtPJNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtPJEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtPJSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtPJFone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtPJFone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbCnpj)
                                    .addComponent(txtPJCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel32))
                            .addComponent(txtPJRazao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(txtPJNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(txtPJComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(txtPJBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(txtPJCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(cbPJEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(txtPJCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoPJ)
                    .addComponent(btnCancelarPJ)
                    .addComponent(btnPesqPJ)
                    .addComponent(btnSalvarPJ))
                .addContainerGap())
        );

        jTabbedPane3.addTab("Pessoa Juridica", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPJBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPJBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPJBairroActionPerformed

    private void txtPJCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPJCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPJCnpjActionPerformed

    private void txtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroActionPerformed

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void btnPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqActionPerformed
       ClassePrincipal.pesC = new PesquisarClientes();
       ClassePrincipal.p.AreaPrincipal.add(ClassePrincipal.pesC);
       ClassePrincipal.pesC.setVisible(true);
       hide();
    }//GEN-LAST:event_btnPesqActionPerformed

    private void btnPesqPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqPJActionPerformed
       ClassePrincipal.pesC = new PesquisarClientes();
       ClassePrincipal.p.AreaPrincipal.add(ClassePrincipal.pesC);
       ClassePrincipal.pesC.setVisible(true);
       hide();
    }//GEN-LAST:event_btnPesqPJActionPerformed

    private void btnSalvarPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarPJActionPerformed
        String nome = txtPJNome.getText();
        String responsavel = txtResponsavel.getText();
        String email = txtPJEmail.getText();
        String senha = txtPJSenha.getText();
        String fone1 = txtPJFone1.getText();
        String cel = txtPJFone2.getText();
        String cnpj = txtPJCnpj.getText();
        String razao_social =txtPJRazao.getText();
        
        String rua = txtPJRua.getText();
        int numero = Integer.parseInt(txtPJNumero.getText());
        String complemento = txtPJComplemento.getText();
        String bairro = txtPJBairro.getText();
        String cidade = txtPJCidade.getText();
        String uf = cbPJEstados.getSelectedItem().toString();
        String cep = txtPJCep.getText();

        ClienteDAO cDAO = new ClienteDAO();
        EnderecosDAO eDAO = new EnderecosDAO();
        PJuridicaDAO pfDAO = new PJuridicaDAO();
        
        try {
            //Utiliza o metodo inserir da classe DB para inserir os dados no banco
            eDAO.inserirEndereco(rua,numero,complemento,bairro,cidade,uf,cep);
            } catch (ParseException ex) {
            Logger.getLogger(CadastrarCliente.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("DEU MERDA AQUI! cadastrar Cliente");
        }
        
        
        try {
            //Utiliza o metodo inserir da classe DB para inserir os dados no banco
            
            cDAO.inserirClientePF(nome,email,senha,fone1,cel);
            } catch (ParseException ex) {
            Logger.getLogger(CadastrarCliente.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("DEU MERDA AQUI! cadastrar Cliente");
        }
        
        try {
            //Utiliza o metodo inserir da classe DB para inserir os dados no banco
            pfDAO.inserirPJuridica(cnpj,responsavel,razao_social);
            } catch (ParseException ex) {
            Logger.getLogger(CadastrarCliente.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("DEU MERDA AQUI! cadastrar Cliente");
        } catch (SQLException ex) {
            Logger.getLogger(CadastrarCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        btnSalvar.setVisible(false);
        btnCancel.setVisible(false);
        
        btnNovo.setEnabled(true);
        btnPesq.setEnabled(true);
        
        btnCancelarPJ.setVisible(false);
        btnNovoPJ.setEnabled(true);
        btnPesqPJ.setEnabled(true);
        btnSalvarPJ.setVisible(false);
        
        
        txtBairro.setEnabled(false);
        txtCep.setEnabled(false);
        txtCidade.setEnabled(false);
        txtComplemento.setEnabled(false);
        txtCpf.setEnabled(false);
        txtEmail.setEnabled(false);
        txtFone1.setEnabled(false);
        txtFone2.setEnabled(false);
        txtNome.setEnabled(false);
        txtNumero.setEnabled(false);
        txtRua.setEnabled(false);
        txtSenha.setEnabled(false);
        jDateChooser1.setEnabled(false);
        
        cbEstado.setEnabled(false);
        cbPJEstados.setEnabled(false);
        
        txtPJCep.setEnabled(false);
        txtPJCidade.setEnabled(false);
        txtPJCnpj.setEnabled(false);
        txtPJComplemento.setEnabled(false);
        txtPJEmail.setEnabled(false);
        txtPJFone1.setEnabled(false);
        txtPJFone2.setEnabled(false);
        txtPJNome.setEnabled(false);
        txtPJNumero.setEnabled(false);
        txtPJRazao.setEnabled(false);
        txtPJSenha.setEnabled(false);
        txtPJRua.setEnabled(false);
        txtResponsavel.setEnabled(false);
        txtPJBairro.setEnabled(false);
        
        txtBairro.setText("");
        txtCep.setText("");
        txtCidade.setText("");
        txtComplemento.setText("");
        txtCpf.setText("");
        txtEmail.setText("");
        txtFone1.setText("");
        txtFone2.setText("");
        txtNome.setText("");
        txtNumero.setText("");
        txtRua.setText("");
        txtSenha.setText("");
        
        
        txtPJCep.setText("");
        txtPJCidade.setText("");
        txtPJCnpj.setText("");
        txtPJComplemento.setText("");
        txtPJEmail.setText("");
        txtPJFone1.setText("");
        txtPJFone2.setText("");
        txtPJNome.setText("");
        txtPJNumero.setText("");
        txtPJRazao.setText("");
        txtPJSenha.setText("");
        txtPJRua.setText("");
        txtResponsavel.setText("");
        txtPJBairro.setText("");
        
    }//GEN-LAST:event_btnSalvarPJActionPerformed

    private void btnCancelarPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPJActionPerformed
        btnSalvar.setVisible(false);
        btnCancel.setVisible(false);
        
        btnNovo.setEnabled(true);
        btnPesq.setEnabled(true);
        
        btnCancelarPJ.setVisible(false);
        btnNovoPJ.setEnabled(true);
        btnPesqPJ.setEnabled(true);
        btnSalvarPJ.setVisible(false);
        
        
        
        txtBairro.setEnabled(false);
        txtCep.setEnabled(false);
        txtCidade.setEnabled(false);
        txtComplemento.setEnabled(false);
        txtCpf.setEnabled(false);
        txtEmail.setEnabled(false);
        txtFone1.setEnabled(false);
        txtFone2.setEnabled(false);
        txtNome.setEnabled(false);
        txtNumero.setEnabled(false);
        txtRua.setEnabled(false);
        txtSenha.setEnabled(false);
        jDateChooser1.setEnabled(false);
        
        cbEstado.setEnabled(false);
        cbPJEstados.setEnabled(false);
        
        txtPJCep.setEnabled(false);
        txtPJCidade.setEnabled(false);
        txtPJCnpj.setEnabled(false);
        txtPJComplemento.setEnabled(false);
        txtPJEmail.setEnabled(false);
        txtPJFone1.setEnabled(false);
        txtPJFone2.setEnabled(false);
        txtPJNome.setEnabled(false);
        txtPJNumero.setEnabled(false);
        txtPJRazao.setEnabled(false);
        txtPJSenha.setEnabled(false);
        txtPJRua.setEnabled(false);
        txtResponsavel.setEnabled(false);
        txtPJBairro.setEnabled(false);
        
        txtBairro.setText("");
        txtCep.setText("");
        txtCidade.setText("");
        txtComplemento.setText("");
        txtCpf.setText("");
        txtEmail.setText("");
        txtFone1.setText("");
        txtFone2.setText("");
        txtNome.setText("");
        txtNumero.setText("");
        txtRua.setText("");
        txtSenha.setText("");
        
        
        txtPJCep.setText("");
        txtPJCidade.setText("");
        txtPJCnpj.setText("");
        txtPJComplemento.setText("");
        txtPJEmail.setText("");
        txtPJFone1.setText("");
        txtPJFone2.setText("");
        txtPJNome.setText("");
        txtPJNumero.setText("");
        txtPJRazao.setText("");
        txtPJSenha.setText("");
        txtPJRua.setText("");
        txtResponsavel.setText("");
        txtPJBairro.setText("");
        
        
    // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarPJActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        btnNovo.setEnabled(true);
        btnPesq.setEnabled(true);
        btnSalvar.setVisible(false);
        btnCancel.setVisible(false);
        
        btnNovoPJ.setEnabled(true);
        btnPesqPJ.setEnabled(true);
        btnSalvarPJ.setVisible(false);
        btnCancelarPJ.setVisible(false);
        
        txtBairro.setEnabled(false);
        txtCep.setEnabled(false);
        txtCidade.setEnabled(false);
        txtComplemento.setEnabled(false);
        txtCpf.setEnabled(false);
        txtEmail.setEnabled(false);
        txtFone1.setEnabled(false);
        txtFone2.setEnabled(false);
        txtNome.setEnabled(false);
        txtNumero.setEnabled(false);
        txtRua.setEnabled(false);
        txtSenha.setEnabled(false);
        jDateChooser1.setEnabled(false);
        
        cbEstado.setEnabled(false);
        cbPJEstados.setEnabled(false);
        
        txtPJCep.setEnabled(false);
        txtPJCidade.setEnabled(false);
        txtPJCnpj.setEnabled(false);
        txtPJComplemento.setEnabled(false);
        txtPJEmail.setEnabled(false);
        txtPJFone1.setEnabled(false);
        txtPJFone2.setEnabled(false);
        txtPJNome.setEnabled(false);
        txtPJNumero.setEnabled(false);
        txtPJRazao.setEnabled(false);
        txtPJSenha.setEnabled(false);
        txtPJRua.setEnabled(false);
        txtResponsavel.setEnabled(false);
        txtPJBairro.setEnabled(false);
        
        txtBairro.setText("");
        txtCep.setText("");
        txtCidade.setText("");
        txtComplemento.setText("");
        txtCpf.setText("");
        txtEmail.setText("");
        txtFone1.setText("");
        txtFone2.setText("");
        txtNome.setText("");
        txtNumero.setText("");
        txtRua.setText("");
        txtSenha.setText("");
        
        
        txtPJCep.setText("");
        txtPJCidade.setText("");
        txtPJCnpj.setText("");
        txtPJComplemento.setText("");
        txtPJEmail.setText("");
        txtPJFone1.setText("");
        txtPJFone2.setText("");
        txtPJNome.setText("");
        txtPJNumero.setText("");
        txtPJRazao.setText("");
        txtPJSenha.setText("");
        txtPJRua.setText("");
        txtResponsavel.setText("");
        txtPJBairro.setText("");
        
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        String nome = txtNome.getText();
        String email = txtEmail.getText();
        String senha = txtSenha.getText();
        String fone1 = txtFone1.getText();
        String cel = txtFone2.getText();

        String cpf = txtCpf.getText();
        String data_nasc = jDateChooser1.getDateFormatString();

        String rua = txtRua.getText();
        int numero = Integer.parseInt(txtNumero.getText());
        String complemento = txtComplemento.getText();
        String bairro = txtBairro.getText();
        String cidade = txtCidade.getText();
        String uf = cbEstado.getSelectedItem().toString();
        String cep = txtCep.getText();
      

        //String dataNasc = cbDataNasc.getSelectedItem().toString();

        ClienteDAO cDAO = new ClienteDAO();
        EnderecosDAO eDAO = new EnderecosDAO();
        PFisicaDAO pfDAO = new PFisicaDAO();

        try {
            //Utiliza o metodo inserir da classe DB para inserir os dados no banco
            eDAO.inserirEndereco(rua,numero,complemento,bairro,cidade,uf,cep);
        } catch (ParseException ex) {
            Logger.getLogger(CadastrarCliente.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("DEU MERDA AQUI! cadastrar Cliente");
        }

        try {
            //Utiliza o metodo inserir da classe DB para inserir os dados no banco

            cDAO.inserirClientePF(nome,email,senha,fone1,cel);
        } catch (ParseException ex) {
            Logger.getLogger(CadastrarCliente.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("DEU MERDA AQUI! cadastrar Cliente");
        }

        try {
            //Utiliza o metodo inserir da classe DB para inserir os dados no banco
            pfDAO.inserirPFisica(cpf,data_nasc);
        } catch (ParseException ex) {
            Logger.getLogger(CadastrarCliente.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("DEU MERDA AQUI! cadastrar Cliente");
        }
        
        //Desabilita campos e limpa.
        btnSalvar.setVisible(false);
        btnCancel.setVisible(false);
        btnNovo.setEnabled(true);
        btnPesq.setEnabled(true);
        btnPesqPJ.setEnabled(true);
        btnPesqPJ.setEnabled(true);
        
        
        
        txtBairro.setEnabled(false);
        txtCep.setEnabled(false);
        txtCidade.setEnabled(false);
        txtComplemento.setEnabled(false);
        txtCpf.setEnabled(false);
        txtEmail.setEnabled(false);
        txtFone1.setEnabled(false);
        txtFone2.setEnabled(false);
        txtNome.setEnabled(false);
        txtNumero.setEnabled(false);
        txtRua.setEnabled(false);
        txtSenha.setEnabled(false);
        jDateChooser1.setEnabled(false);
        
        cbEstado.setEnabled(false);
        cbPJEstados.setEnabled(false);
        
        txtPJCep.setEnabled(false);
        txtPJCidade.setEnabled(false);
        txtPJCnpj.setEnabled(false);
        txtPJComplemento.setEnabled(false);
        txtPJEmail.setEnabled(false);
        txtPJFone1.setEnabled(false);
        txtPJFone2.setEnabled(false);
        txtPJNome.setEnabled(false);
        txtPJNumero.setEnabled(false);
        txtPJRazao.setEnabled(false);
        txtPJSenha.setEnabled(false);
        txtPJRua.setEnabled(false);
        txtResponsavel.setEnabled(false);
        txtPJBairro.setEnabled(false);
        
        txtBairro.setText("");
        txtCep.setText("");
        txtCidade.setText("");
        txtComplemento.setText("");
        txtCpf.setText("");
        txtEmail.setText("");
        txtFone1.setText("");
        txtFone2.setText("");
        txtNome.setText("");
        txtNumero.setText("");
        txtRua.setText("");
        txtSenha.setText("");
        
        
        txtPJCep.setText("");
        txtPJCidade.setText("");
        txtPJCnpj.setText("");
        txtPJComplemento.setText("");
        txtPJEmail.setText("");
        txtPJFone1.setText("");
        txtPJFone2.setText("");
        txtPJNome.setText("");
        txtPJNumero.setText("");
        txtPJRazao.setText("");
        txtPJSenha.setText("");
        txtPJRua.setText("");
        txtResponsavel.setText("");
        txtPJBairro.setText("");
        
        txtNome.grabFocus();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnNovoPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoPJActionPerformed
        btnSalvar.setVisible(false);
        btnCancel.setVisible(false);
        btnNovo.setEnabled(false);
        btnPesq.setEnabled(false);
        
        btnNovoPJ.setEnabled(false);
        btnCancelarPJ.setVisible(true);
        btnSalvarPJ.setVisible(true);
        btnPesqPJ.setEnabled(false);
        
        txtBairro.setEnabled(false);
        txtCep.setEnabled(false);
        txtCidade.setEnabled(false);
        txtComplemento.setEnabled(false);
        txtCpf.setEnabled(false);
        txtEmail.setEnabled(false);
        txtFone1.setEnabled(false);
        txtFone2.setEnabled(false);
        txtNome.setEnabled(false);
        txtNumero.setEnabled(false);
        txtRua.setEnabled(false);
        txtSenha.setEnabled(false);
        jDateChooser1.setEnabled(false);
        
        cbEstado.setEnabled(false);
        cbPJEstados.setEnabled(true);
        
        txtPJCep.setEnabled(true);
        txtPJCidade.setEnabled(true);
        txtPJCnpj.setEnabled(true);
        txtPJComplemento.setEnabled(true);
        txtPJEmail.setEnabled(true);
        txtPJFone1.setEnabled(true);
        txtPJFone2.setEnabled(true);
        txtPJNome.setEnabled(true);
        txtPJNumero.setEnabled(true);
        txtPJRazao.setEnabled(true);
        txtPJSenha.setEnabled(true);
        txtPJRua.setEnabled(true);
        txtResponsavel.setEnabled(true);
        txtPJBairro.setEnabled(true);
        
        txtBairro.setText("");
        txtCep.setText("");
        txtCidade.setText("");
        txtComplemento.setText("");
        txtCpf.setText("");
        txtEmail.setText("");
        txtFone1.setText("");
        txtFone2.setText("");
        txtNome.setText("");
        txtNumero.setText("");
        txtRua.setText("");
        txtSenha.setText("");
        
        
        txtPJCep.setText("");
        txtPJCidade.setText("");
        txtPJCnpj.setText("");
        txtPJComplemento.setText("");
        txtPJEmail.setText("");
        txtPJFone1.setText("");
        txtPJFone2.setText("");
        txtPJNome.setText("");
        txtPJNumero.setText("");
        txtPJRazao.setText("");
        txtPJSenha.setText("");
        txtPJRua.setText("");
        txtResponsavel.setText("");
        txtPJBairro.setText("");
        
        txtResponsavel.grabFocus();
    }//GEN-LAST:event_btnNovoPJActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        btnSalvar.setVisible(true);
        btnCancel.setVisible(true);
        btnNovo.setEnabled(false);
        btnPesq.setEnabled(false);
        btnNovoPJ.setEnabled(false);
        btnCancelarPJ.setVisible(false);
        btnSalvarPJ.setVisible(false);
        btnPesqPJ.setEnabled(false);
        
        txtBairro.setEnabled(true);
        txtCep.setEnabled(true);
        txtCidade.setEnabled(true);
        txtComplemento.setEnabled(true);
        txtCpf.setEnabled(true);
        txtEmail.setEnabled(true);
        txtFone1.setEnabled(true);
        txtFone2.setEnabled(true);
        txtNome.setEnabled(true);
        txtNumero.setEnabled(true);
        txtRua.setEnabled(true);
        txtSenha.setEnabled(true);
        jDateChooser1.setEnabled(true);
        
        cbEstado.setEnabled(true);
        cbPJEstados.setEnabled(false);
        
        txtPJCep.setEnabled(false);
        txtPJCidade.setEnabled(false);
        txtPJCnpj.setEnabled(false);
        txtPJComplemento.setEnabled(false);
        txtPJEmail.setEnabled(false);
        txtPJFone1.setEnabled(false);
        txtPJFone2.setEnabled(false);
        txtPJNome.setEnabled(false);
        txtPJNumero.setEnabled(false);
        txtPJRazao.setEnabled(false);
        txtPJSenha.setEnabled(false);
        txtPJRua.setEnabled(false);
        txtResponsavel.setEnabled(false);
        txtPJBairro.setEnabled(false);
        
        txtBairro.setText("");
        txtCep.setText("");
        txtCidade.setText("");
        txtComplemento.setText("");
        txtCpf.setText("");
        txtEmail.setText("");
        txtFone1.setText("");
        txtFone2.setText("");
        txtNome.setText("");
        txtNumero.setText("");
        txtRua.setText("");
        txtSenha.setText("");
        
        
        txtPJCep.setText("");
        txtPJCidade.setText("");
        txtPJCnpj.setText("");
        txtPJComplemento.setText("");
        txtPJEmail.setText("");
        txtPJFone1.setText("");
        txtPJFone2.setText("");
        txtPJNome.setText("");
        txtPJNumero.setText("");
        txtPJRazao.setText("");
        txtPJSenha.setText("");
        txtPJRua.setText("");
        txtResponsavel.setText("");
        txtPJBairro.setText("");
        
        txtNome.grabFocus();
    }//GEN-LAST:event_btnNovoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Logo;
    public javax.swing.JButton btnCancel;
    public javax.swing.JButton btnCancelarPJ;
    public javax.swing.JButton btnNovo;
    public javax.swing.JButton btnNovoPJ;
    public javax.swing.JButton btnPesq;
    public javax.swing.JButton btnPesqPJ;
    public javax.swing.JButton btnSalvar;
    public javax.swing.JButton btnSalvarPJ;
    public javax.swing.JComboBox cbEstado;
    public javax.swing.JComboBox cbPJEstados;
    public com.toedter.calendar.JDateChooser jDateChooser1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel25;
    public javax.swing.JLabel jLabel26;
    public javax.swing.JLabel jLabel27;
    public javax.swing.JLabel jLabel28;
    public javax.swing.JLabel jLabel29;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel30;
    public javax.swing.JLabel jLabel31;
    public javax.swing.JLabel jLabel32;
    public javax.swing.JLabel jLabel33;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JSeparator jSeparator2;
    public javax.swing.JTabbedPane jTabbedPane3;
    public javax.swing.JLabel lbCnpj;
    public javax.swing.JTextField txtBairro;
    public javax.swing.JTextField txtCep;
    public javax.swing.JTextField txtCidade;
    public javax.swing.JTextField txtComplemento;
    public javax.swing.JTextField txtCpf;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JFormattedTextField txtFone1;
    public javax.swing.JFormattedTextField txtFone2;
    public javax.swing.JTextField txtNome;
    public javax.swing.JTextField txtNumero;
    public javax.swing.JTextField txtPJBairro;
    public javax.swing.JTextField txtPJCep;
    public javax.swing.JTextField txtPJCidade;
    public javax.swing.JTextField txtPJCnpj;
    public javax.swing.JTextField txtPJComplemento;
    public javax.swing.JTextField txtPJEmail;
    public javax.swing.JFormattedTextField txtPJFone1;
    public javax.swing.JFormattedTextField txtPJFone2;
    public javax.swing.JTextField txtPJNome;
    public javax.swing.JTextField txtPJNumero;
    public javax.swing.JTextField txtPJRazao;
    public javax.swing.JTextField txtPJRua;
    public javax.swing.JTextField txtPJSenha;
    public javax.swing.JTextField txtResponsavel;
    public javax.swing.JTextField txtRua;
    public javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
