/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.atendimento;

import Classes.ClassePrincipal;
import Classes.Cliente;
import Classes.Endereco;
import Classes.FuncionarioLogado;
import DAO.ClienteDAO;
import DAO.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import telas.principal.Principal;
import telas.supervisao.AlterarCliente;

/**
 *
 * @author User
 */
public class PesquisarClientes extends javax.swing.JInternalFrame {
    
    
    DefaultTableModel modelo;
    
    //AlterarCliente alterarCadastroPF = new AlterarCliente();
    
    /**
     * Creates new form PesquisarClientes
     */
    public PesquisarClientes() {
        initComponents();
        modelo = (DefaultTableModel) tabela.getModel();
        tabela.setAutoCreateRowSorter(true);
        btnAlt.setVisible(false);
        ClassePrincipal.c = new Cliente();
        ClassePrincipal.alt = new AlterarCliente();
        ClassePrincipal.e = new Endereco();
                
//        FuncionarioLogado ClassePrincipal.f = new FuncionarioLogado();
        
        
    }

    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        painelPesquisar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tabelaroll = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txProcurar = new javax.swing.JTextField();
        PeinelAlt = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtAltNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAltEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAltSenha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAltTel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAltCel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAltEnd = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        btnAlt = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Pesquisar Clientes");

        jLabel1.setText("Pesquisar: ");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "E-mail", "Senha", "Fone", "Celular", "End ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabelaMouseReleased(evt);
            }
        });
        tabelaroll.setViewportView(tabela);

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome: ");

        txtAltNome.setEnabled(false);
        txtAltNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAltNomeActionPerformed(evt);
            }
        });

        jLabel3.setText("Email: ");

        txtAltEmail.setEnabled(false);
        txtAltEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAltEmailActionPerformed(evt);
            }
        });

        jLabel4.setText("Senha: ");

        txtAltSenha.setEnabled(false);

        jLabel5.setText("Telefone:");

        txtAltTel.setEnabled(false);

        jLabel6.setText("Celular: ");

        txtAltCel.setEnabled(false);
        txtAltCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAltCelActionPerformed(evt);
            }
        });

        jLabel7.setText("Endereço: ");

        txtAltEnd.setEnabled(false);

        jButton2.setText("Ver Endereço");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAltEmail)
                    .addComponent(txtAltNome)
                    .addComponent(txtAltSenha)
                    .addComponent(txtAltTel)
                    .addComponent(txtAltCel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtAltEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAltNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAltEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAltSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAltTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAltCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAltEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PeinelAltLayout = new javax.swing.GroupLayout(PeinelAlt);
        PeinelAlt.setLayout(PeinelAltLayout);
        PeinelAltLayout.setHorizontalGroup(
            PeinelAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PeinelAltLayout.setVerticalGroup(
            PeinelAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnAlt.setText("Alterar Cliente");
        btnAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPesquisarLayout = new javax.swing.GroupLayout(painelPesquisar);
        painelPesquisar.setLayout(painelPesquisarLayout);
        painelPesquisarLayout.setHorizontalGroup(
            painelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesquisarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPesquisarLayout.createSequentialGroup()
                        .addComponent(PeinelAlt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlt))
                    .addComponent(tabelaroll, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                    .addGroup(painelPesquisarLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txProcurar)))
                .addContainerGap())
            .addGroup(painelPesquisarLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelPesquisarLayout.setVerticalGroup(
            painelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesquisarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabelaroll, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelPesquisarLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PeinelAlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAlt))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        atualizaTabela();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabelaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseReleased
        
        int linha = tabela.getSelectedRow();
        
        ClassePrincipal.c.setCliente_id(Integer.parseInt((String) tabela.getValueAt(linha, 0)));
        ClassePrincipal.c.setNome(tabela.getValueAt(linha, 1).toString());
        ClassePrincipal.c.setEmail(tabela.getValueAt(linha, 2).toString());
        ClassePrincipal.c.setSenha(tabela.getValueAt(linha, 3).toString());
        ClassePrincipal.c.setFone1(tabela.getValueAt(linha, 4).toString());
        ClassePrincipal.c.setCel(tabela.getValueAt(linha, 5).toString());
        ClassePrincipal.c.setEndereco_end_id(Integer.parseInt((String) tabela.getValueAt(linha, 6)));
        
        //mostrando Previa para Operdador
        txtAltNome.setText(tabela.getValueAt(linha, 1).toString());
        txtAltEmail.setText(tabela.getValueAt(linha, 2).toString());
        txtAltSenha.setText(tabela.getValueAt(linha, 3).toString());
        txtAltTel.setText(tabela.getValueAt(linha, 4).toString());
        txtAltCel.setText(tabela.getValueAt(linha, 5).toString());
        txtAltEnd.setText(tabela.getValueAt(linha, 6).toString());
        
        
        if(ClassePrincipal.f.getNivel()>=3){btnAlt.setVisible(true);}
        System.out.println(ClassePrincipal.c.getNome());
         
    }//GEN-LAST:event_tabelaMouseReleased

    private void txtAltNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAltNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltNomeActionPerformed

    private void txtAltEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAltEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltEmailActionPerformed

    private void txtAltCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAltCelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltCelActionPerformed

    private void btnAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltActionPerformed
       
        int criterio;
        Conexao x = new Conexao();
        criterio = ClassePrincipal.c.getEndereco_end_id();
        String sql = "select * from mydb.endereco where END_ID=" + criterio + ";";
        Connection conexao = x.Conectar();
        
        try (PreparedStatement stm = conexao.prepareStatement(sql);
                ResultSet rs = stm.executeQuery()) {

            while (rs.next()) {
                String rua = rs.getString("RUA");
                String numero = rs.getString("NUMERO");
                String complemento = rs.getString("COMPLEMENTO");
                String bairro = rs.getString("BAIRRO");
                String cidade = rs.getString("CIDADE");
                String uf = rs.getString("UF");
                String cep = rs.getString("CEP");
                
                
                ClassePrincipal.e.setRua(rua);
                ClassePrincipal.e.setNumero(numero);
                ClassePrincipal.e.setComplemento(complemento);
                ClassePrincipal.e.setBairro(bairro);
                ClassePrincipal.e.setCidade(cidade);
                ClassePrincipal.e.setUf(uf);
                ClassePrincipal.e.setCep(cep);
                
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
                
                ClassePrincipal.alt.txtNome.setText(ClassePrincipal.c.getNome());
                ClassePrincipal.alt.txtEmail.setText(ClassePrincipal.c.getEmail());
                ClassePrincipal.alt.txtSenha.setText(ClassePrincipal.c.getSenha());
                ClassePrincipal.alt.txtTel.setText(ClassePrincipal.c.getFone1());
                ClassePrincipal.alt.txtCel.setText(ClassePrincipal.c.getCel());
                ClassePrincipal.alt.txtRua.setText(ClassePrincipal.e.getRua());
                ClassePrincipal.alt.txtNumero.setText(ClassePrincipal.e.getNumero());
                ClassePrincipal.alt.txtComp.setText(ClassePrincipal.e.getComplemento());
                ClassePrincipal.alt.txtBairro.setText(ClassePrincipal.e.getBairro());
                ClassePrincipal.alt.txtCidade.setText(ClassePrincipal.e.getCidade());
                ClassePrincipal.alt.cbUf.setSelectedItem(ClassePrincipal.e.getUf());
                ClassePrincipal.alt.txtCep.setText(ClassePrincipal.e.getCep());
                
                ClassePrincipal.alt.setVisible(true);
    }//GEN-LAST:event_btnAltActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PeinelAlt;
    private javax.swing.JButton btnAlt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel painelPesquisar;
    private javax.swing.JTable tabela;
    private javax.swing.JScrollPane tabelaroll;
    private javax.swing.JTextField txProcurar;
    private javax.swing.JTextField txtAltCel;
    private javax.swing.JTextField txtAltEmail;
    private javax.swing.JTextField txtAltEnd;
    private javax.swing.JTextField txtAltNome;
    private javax.swing.JTextField txtAltSenha;
    private javax.swing.JTextField txtAltTel;
    // End of variables declaration//GEN-END:variables
   
    public void atualizaTabela() {
        String criterio;
        criterio = txProcurar.getText();
        /*Pega os dados no banco de acordo com a pesquisa/palavra digitada
         *no campo de pesquisa
         *
         */
        ClienteDAO listaContatos = new ClienteDAO();
        ResultSet resultado = listaContatos.retornaDados(criterio);
        //Desliga o auto-ajuste das colunas
        tabela.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        tabela.getColumnModel().getColumn(0).setPreferredWidth(40);
        tabela.getColumnModel().getColumn(1).setPreferredWidth(170);
        tabela.getColumnModel().getColumn(2).setPreferredWidth(170);
        tabela.getColumnModel().getColumn(3).setPreferredWidth(100);
        tabela.getColumnModel().getColumn(4).setPreferredWidth(140);
        tabela.getColumnModel().getColumn(5).setPreferredWidth(140);
        tabela.getColumnModel().getColumn(6).setPreferredWidth(50);

        //limpa a tabela caso exista algum registro
        modelo.setRowCount(0);
        //preenche a tabela com os dados que vem do ResultSet
        try {
            while (resultado.next()) {
                String codigo = resultado.getString("CLIENTE_ID");
                String nome = resultado.getString("NOME");
                String email = resultado.getString("EMAIL");
                String senha = resultado.getString("SENHA");
                String fone = resultado.getString("FONE1");
                String celular = resultado.getString("CEL");
                String endereco_id = resultado.getString("ENDERECO_END_ID");
                modelo.addRow(new String[]{codigo, nome, email, senha, fone, celular, endereco_id});
            }
            listaContatos.fechaConexao();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
       
            
            
        }
        
    
   


}
